version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          RAILS_ENV: test

      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: tms_test
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.1.4
      - run: bundle install
